### ISSUE TITLE
现在似乎不能用了

### ISSUE THREAD

**Issue by diyanqi** [bossbaby2005/luogu-discuss-log#10]
如题，对于大多数帖子，点击保存时会出现“帖子已删除”

**Comment by eventlOwOp** [comment]
我这边测试正常, 你的问题?

**Comment by diyanqi** [comment]
可能是我的问题，但是我想知道在这个仓库上的是否是最新源码？因为我看到 `功能请求和贡献请Github开issue, 但是github的源代码由于太咕没有同步, 需要可以洛谷私信联系获取` 。如果有更新的源码，是否可以劳驾发我一份？

**Comment by diyanqi** [comment]
对不起，是我大意了，忘记给 `config.php` 加上cookie了。希望在README里加一下（
抱歉打扰您了

**Comment by eventlOwOp** [comment]
这个应该是非常新的版本了, 和部署的应该基本没有差别.
